const API_BASE = "http://127.0.0.1:8000/api";
const state = { dashboard: null, components: [], projects: [], projectBoms: new Map(), componentRows: [], sharedRows: [], currentComponentSort: "part" };
const $ = (selector) => document.querySelector(selector);
const text = (value) => value === null || value === undefined || value === "" ? "Not provided" : value;

async function request(path) { const response = await fetch(`${API_BASE}${path}`); if (!response.ok) { const payload = await response.json().catch(() => ({})); throw new Error(payload.detail || `Request failed (${response.status})`); } return response.json(); }
function make(tag, className, value) { const element = document.createElement(tag); if (className) element.className = className; if (value !== undefined) element.textContent = value; return element; }
function clear(node) { node.replaceChildren(); }
function showView(name) { document.body.classList.toggle("dashboard-active", name === "dashboard"); document.querySelectorAll(".view").forEach((view) => view.classList.toggle("hidden", view.dataset.view !== name)); document.querySelectorAll(".nav-link").forEach((link) => link.classList.toggle("active", link.dataset.nav === name)); const copy = { dashboard:["BOM overview","Understand which components are required and where they are used."], components:["Component directory",""], projects:["Projects","Inspect the imported BOM requirements for each project."], shared:["Shared components","Review components required by more than one project."] }[name]; $("#page-title").textContent = copy[0]; $("#page-description").textContent = copy[1]; }
function goTo(name) { location.hash = name; showView(name); }
function projectTags(projects) { const container = make("div", "tag-list"); projects.forEach((project) => container.append(make("span", "tag", project.name))); return container; }
function buildRelationships() { const byPart = new Map(); for (const project of state.projects) { for (const item of state.projectBoms.get(project.id) || []) { let row = byPart.get(item.component_id); if (!row) { row = { ...item, projects: [], totalRequired: 0 }; byPart.set(item.component_id, row); } row.projects.push({ id: project.id, name: project.name, quantity: item.quantity_required }); row.totalRequired += item.quantity_required; } } state.componentRows = state.components.map((component) => byPart.get(component.id) || { ...component, projects: [], totalRequired: 0 }); state.sharedRows = state.componentRows.filter((component) => component.projects.length > 1); }
function renderBarChart(container, projects, valueKey, unitLabel) {
  clear(container);
  const maximum = Math.max(...projects.map((project) => project[valueKey]), 1);
  projects.forEach((project) => {
    const row = make("div", "chart-row");
    const name = make("span", "chart-label", project.name); name.title = project.name;
    const track = make("div", "chart-track");
    const bar = make("button", "chart-bar");
    const value = project[valueKey];
    bar.style.setProperty("--bar-size", `${(value / maximum) * 100}%`);
    bar.title = `${project.name}: ${value} ${unitLabel}`;
    bar.setAttribute("aria-label", `${project.name}: ${value} ${unitLabel}. Open project details.`);
    bar.addEventListener("click", () => openProject(project.id));
    track.append(bar);
    row.append(name, track, make("span", "chart-value", String(value)));
    container.append(row);
  });
}
function renderUsageOverview() {
  const total = state.componentRows.length, shared = state.sharedRows.length, single = total - shared;
  const percent = total ? (shared / total) * 100 : 0;
  $("#usage-donut").style.setProperty("--shared-percent", `${percent}%`);
  $("#usage-donut").title = `${shared} of ${total} components are shared across multiple projects.`;
  $("#usage-percent").textContent = `${Math.round(percent)}%`;
  $("#usage-summary").textContent = `${shared} shared components need cross-project coordination.`;
  $("#usage-detail").textContent = `${single} components are used by one project; ${shared} are used by multiple projects.`;
  const legend = $("#usage-legend"); clear(legend);
  [["#2f80ed", `${single} used by one project`], ["#e99417", `${shared} shared across projects`]].forEach(([color, label]) => { const key = make("span", "usage-key", label); key.style.setProperty("--key-color", color); legend.append(key); });
}
function renderDashboard() { const data = state.dashboard; $("#component-count").textContent = data.component_count; $("#project-count").textContent = data.project_count; $("#bom-count").textContent = data.bom_item_count; $("#shared-count").textContent = state.sharedRows.length; renderBarChart($("#components-chart"), data.projects, "component_count", "components"); renderBarChart($("#units-chart"), data.projects, "total_quantity_required", "required BOM units"); renderUsageOverview(); const projects = $("#dashboard-projects"); clear(projects); data.projects.forEach((project) => { const row = make("button", "summary-row"); const left = make("span"); left.append(make("strong", "", project.name), make("span", "", `${project.component_count} components`)); row.append(left, make("span", "", `${project.total_quantity_required} required units`)); row.addEventListener("click", () => openProject(project.id)); projects.append(row); }); const shared = $("#dashboard-shared"); clear(shared); state.sharedRows.slice(0, 5).forEach((component) => { const row = make("button", "summary-row"); const left = make("span"); left.append(make("strong", "part-number", component.manufacturer_part_number), make("span", "", component.projects.map((project) => project.name).join(", "))); row.append(left, make("span", "", `${component.totalRequired} units`)); row.addEventListener("click", () => goTo("shared")); shared.append(row); }); if (!state.sharedRows.length) shared.append(make("p", "empty-cell", "No shared components were found in the imported BOM data.")); }
function renderProjects() { const grid = $("#project-cards"); clear(grid); state.dashboard.projects.forEach((project) => { const card = make("button", "project-card"); card.append(make("h3", "", project.name)); const stats = make("div", "project-stats"); const components = make("span"); components.append(make("strong", "", String(project.component_count)), document.createTextNode("components")); const units = make("span"); units.append(make("strong", "", String(project.total_quantity_required)), document.createTextNode("required BOM units")); stats.append(components, units); card.append(stats, make("small", "", "Open project BOM requirements")); card.addEventListener("click", () => openProject(project.id)); grid.append(card); }); }
function openProject(projectId) { goTo("projects"); const project = state.dashboard.projects.find((entry) => entry.id === projectId); const items = state.projectBoms.get(projectId) || []; $("#project-detail-title").textContent = `${project.name} BOM`; $("#project-detail-description").textContent = `${project.component_count} component entries and ${project.total_quantity_required} total required BOM units. These are not stock quantities.`; const body = $("#project-bom-rows"); clear(body); if (!items.length) { const row = document.createElement("tr"); const cell = make("td", "empty-cell", "No BOM items are available for this project."); cell.colSpan = 5; row.append(cell); body.append(row); } items.forEach((item) => { const row = document.createElement("tr"); row.append(make("td", "part-number", item.manufacturer_part_number), make("td", "", text(item.description)), make("td", "", text(item.manufacturer)), make("td", "", String(item.quantity_required)), make("td", "", text(item.reference_designators))); body.append(row); }); $("#project-detail").classList.remove("hidden"); $("#project-detail").scrollIntoView({ behavior: "smooth", block: "start" }); }
function renderComponents() { const query = $("#component-search").value.trim().toLowerCase(); const projectFilter = $("#component-project-filter").value; const sort = state.currentComponentSort; const rows = state.componentRows.filter((component) => { const searchable = [component.manufacturer_part_number, component.manufacturer, component.description, component.value, ...component.projects.map((project) => project.name)].join(" ").toLowerCase(); return searchable.includes(query) && (!projectFilter || component.projects.some((project) => String(project.id) === projectFilter)); }).sort((a,b) => sort === "manufacturer" ? text(a.manufacturer).localeCompare(text(b.manufacturer)) : sort === "projects" ? b.projects.length-a.projects.length || a.manufacturer_part_number.localeCompare(b.manufacturer_part_number) : sort === "quantity" ? b.totalRequired-a.totalRequired || a.manufacturer_part_number.localeCompare(b.manufacturer_part_number) : a.manufacturer_part_number.localeCompare(b.manufacturer_part_number)); $("#component-results").textContent = `${rows.length} of ${state.componentRows.length} components`; const body = $("#component-rows"); clear(body); if (!rows.length) { const row = document.createElement("tr"); const cell = make("td", "empty-cell", "No components match the current search and filters."); cell.colSpan = 5; row.append(cell); body.append(row); return; } rows.forEach((component) => { const row = document.createElement("tr"); const description = make("td"); description.append(make("span", "", text(component.description)), make("small", "", `Value: ${text(component.value)}`)); row.append(make("td", "part-number", component.manufacturer_part_number), make("td", "", text(component.manufacturer)), description); const useCell = document.createElement("td"); useCell.append(projectTags(component.projects)); row.append(useCell, make("td", "", `${component.totalRequired} BOM units`)); body.append(row); }); }
function renderShared() { const query = $("#shared-search").value.trim().toLowerCase(); const rows = state.sharedRows.filter((component) => [component.manufacturer_part_number, component.manufacturer, ...component.projects.map((project) => project.name)].join(" ").toLowerCase().includes(query)).sort((a,b) => b.projects.length-a.projects.length || a.manufacturer_part_number.localeCompare(b.manufacturer_part_number)); $("#shared-results").textContent = `${rows.length} shared components`; const body = $("#shared-rows"); clear(body); if (!rows.length) { const row = document.createElement("tr"); const cell = make("td", "empty-cell", "No shared components match this search."); cell.colSpan = 4; row.append(cell); body.append(row); return; } rows.forEach((component) => { const row = document.createElement("tr"); const projects = document.createElement("td"); projects.append(projectTags(component.projects)); row.append(make("td", "part-number", component.manufacturer_part_number), make("td", "", text(component.manufacturer)), projects, make("td", "", `${component.totalRequired} BOM units`)); body.append(row); }); }
function bindEvents() { window.addEventListener("hashchange", () => showView(location.hash.slice(1) || "dashboard")); document.querySelectorAll("[data-go]").forEach((button) => button.addEventListener("click", () => goTo(button.dataset.go))); $("#component-search").addEventListener("input", renderComponents); $("#component-project-filter").addEventListener("change", renderComponents); $("#component-sort").addEventListener("change", (event) => { state.currentComponentSort = event.target.value; renderComponents(); }); $("[data-component-sort]").addEventListener("click", () => { state.currentComponentSort = "quantity"; $("#component-sort").value = "quantity"; renderComponents(); }); $("#shared-search").addEventListener("input", renderShared); $("#close-project-detail").addEventListener("click", () => $("#project-detail").classList.add("hidden")); }
async function initialize() { try { const [dashboard, components, projects] = await Promise.all([request("/dashboard"), request("/components"), request("/projects")]); state.dashboard = dashboard; state.components = components; state.projects = projects; const boms = await Promise.all(projects.map(async (project) => [project.id, await request(`/projects/${project.id}/bom`)])); boms.forEach(([id, bom]) => state.projectBoms.set(id, bom)); buildRelationships(); const filter = $("#component-project-filter"); projects.forEach((project) => { const option = make("option", "", project.name); option.value = project.id; filter.append(option); }); renderDashboard(); renderProjects(); renderComponents(); renderShared(); $("#app-status").textContent = ""; bindEvents(); showView(location.hash.slice(1) || "dashboard"); } catch (error) { $("#app-status").className = "app-status error"; $("#app-status").textContent = `Could not load BOM data: ${error.message}. Confirm the API is running at http://127.0.0.1:8000 and reload.` } }
initialize();